### ISSUE TITLE
Missing @conda-forge/r ?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/r-semver-feedstock#4]
Most R feedstocks have @conda-forge/r as maintainers. However this one doesn't

Does @conda-forge/r wish to be added?

Would @conda-forge/r-semver be ok with that?

**Comment by ocefpaf** [comment]
> Would @conda-forge/r-semver be ok with that?

I think I'm the only one here 😬 

Sure. At this point I believe it is standard to add the r team too all feedstocks. Kind of core subteamto watch over R recipes. Maybe we should even put a migrator to add the team where it is missing.

What to do think @conda-forge/r?

**Comment by jakirkham** [comment]
Thank you both! 🙏
